### ISSUE TITLE
The relative PE

### ISSUE THREAD

**Issue by Kebii** [SinMDM/SinMDM#17]
Hi, thanks for open-sourcing this excellent work. After reviewing the 'mdm_qnanet.py' code, I couldn't locate the implementation of the relative positional encoding (PE) mentioned in the paper. I'm curious about how this model achieves the generation of diverse results. Do you have any insights to share?

**Comment by SinMDM** [comment]
@Kebii, thank you for your interest!

The relative positional embedding is achieved by adding a bias to the attention heads:
https://github.com/SinMDM/SinMDM/blob/main/models/qna.py#L186C13-L186C13
It is equivalent to relative positional embedding because there is only a single "Query" in the self-attention calculation.

We are happy to answer any further questions.
