### ISSUE TITLE
questions about the limitation

### ISSUE THREAD

**Issue by GuangtaoLyu** [SinMDM/SinMDM#23]
Hello,
Great work.

Another limitation, also common to all single-instance models, is the inability to set generated sub-motions in a specific order, when such order matters (e.g., certain dance moves). This can be addressed by enlarging the receptive field (at the cost of lower diversity).

Can you provide more examples about it.  what is "set generated sub-motions in a specific order".  Why it can be addressed by enlarging the receptive field?

thank you.

**Comment by sigal-raab** [comment]
Hi @GuangtaoLyu, an example of a movement that could be distorted due to a narrow receptive field is the Capoeira Ginga step. This step involves alternating moves between the right and left legs. Once the right leg sub-motion is completed, the subsequent move should be the left leg's, followed by another move with the right leg. However, due to the receptive field perceiving each leg sub-motion as an independent sub-motion, the network might generate a sequence where the dancer repeatedly performs the right leg part, then switches to several repeated times of the left leg part, etc.

A wider receptive field may solve this limitation if the receptive field perceives both legs' sub-motions and learns that a valid sub-motion should contain a transaction between the left leg to the right one or the right leg to the left one.
