### ISSUE TITLE
Question about accelerated generated motions and repetitive patterns when dealing with longer motions

### ISSUE THREAD

**Issue by leob03** [SinMDM/SinMDM#33]
Hi SinMDM team,

First off, awesome work! The idea of leveraging one-shot training to deal with arbitrary motion topologies is brilliant and super useful. It opens up all kinds of possibilities and i know the demand for dealing with animals is high, but also unusual body structures or ones that contains finger and/or facial data, especially when large open-source datasets containing all of that just aren’t around yet.

Now, onto the issue I’ve been having: when I use the pretrained SinMDM models, the generated motions tend to feel “accelerated”. Especially when training on longer motion sequences, the generated sequence samples tend to repeat high-frequency movements multiple times in a row, making them look faster and more compressed than in the original sequences and thus undermines the quality of the generated data.

My insight was that, even-though limiting the receptive field prevents overfitting by focusing on local motion motifs rather than memorizing entire sequences, it also seems to make it harder for the model to capture longer-range dependencies, which could cause these repetitive, high-frequency patterns.

Do you have any suggestions on how to handle this issue—like tweaking kernel sizes, adjusting the attention layers, adding positional embeddings, or other changes? Any insights would be really appreciated. I also have noticed that when dealing with the mixamo dataset, you've slowed down the input motion and then sometimes take every other frame after processing the .bvh files, I was wondering if that was an "engineering fix" for this issue or if there was another specific reason behind that?

Thanks for your time and help!

**Comment by sigal-raab** [comment]
Hi @leob03,
Thank you for your feedback!
Indeed the model does not capture longer-range dependencies, due to its narrow receptive field.
Widening the receptive field can assist in learning longer-range dependencies. Several hyper-parameters affect the width of the receptive field, and each of them has a slightly different impact, so you may need to try different combinations until you find the desired result.
The parameters, ordered from largest impact to smallest, are:
- `--channel_mult`: default is "1". You can try "1,1" or "1,2".
- `--num_res_blocks`: default is 1. You can try 2.
- `--kernel_size`: default is 3. You can try 5 or 7.

I don't see a reason for motions to appear as accelerated. The model learns the exact distribution of a given motion. Maybe the impression of accelerated motion is because there are repeating generated sub-motions?

Re- sampling mixamo every other frame: that's not related to the question at hand. We adopted this sampling from the Ganimator project in order to run a fair comparison (same training conditions) with them. And they used that sampling in order to have faster training.
